version: "3"
services:
  crimehero-server:
    image: crimehero-server:v1.0.0
    restart: always
    ports:
      - 3005:3005
    healthcheck:
      test: "exit 0"
    volumes:
      - crimehero-service-data:/crimehero
      - ./crimehero/logs:/crimehero/logs:rw
      - ./crimehero/.pm2/logs:/crimehero/.pm2/logs:rw
volumes:
  crimehero-service-data:
