version: "3"
services:
  crime-zero-server:
    image: seerviashish17/crime-zero-server:v1.0.0
    restart: always
    ports:
      - 3005:3005
    healthcheck:
      test: "exit 0"
    volumes:
      - crime-zero-service-data:/crimehero
      - ./crimehero/logs:/crimehero/logs:rw
      - ./crimehero/.pm2/logs:/crimehero/.pm2/logs:rw
volumes:
  crime-zero-service-data:
